spring:
  application:
    name: member-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 000802
server:
  port: 11000
pot:
  code:
    generator:
      host: localhost
      port: 3306
      database: member
      username: root
      password: "000802"
      base-package: com.pot.member.service
      module-name: ""
      project-path: /Users/yecao/Project/Pot/Zing/zing/member/member-service
      author: Pot
      table-prefix: member_
      enable-lombok: true
      rest-controller: true
      enabled: true
