spring:
  application:
    name: member-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:member}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
server:
  port: 11000
pot:
  code:
    generator:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:3306}
      database: ${DB_NAME:member}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:}
      base-package: com.pot.member.service
      module-name: ""
      project-path: /Users/yecao/Project/Pot/Zing/zing/member/member-service
      author: Pot
      table-prefix: member_
      enable-lombok: true
      rest-controller: true
      enabled: true
